# Default values for c#.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  pullPolicy: IfNotPresent
service:
  name: gb28181deviceservice
  type: ClusterIP
  externalPort: 8080
  internalPort: 80
resources:
  limits:
    cpu: 1
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 256Mi
ingress:
  enabled: false
serviceAccount:
  create: false
  name: GB28181.platform2016.service
startupConfigs:
  - "--registry=consul"
envConfigs:
    MICRO_SERVER_METADATA: "ServiceTag=HUS"
    LOGGER_LEVEL: 4
versions:
  developTag: v6.0.1.0
  releaseTag: v6.0.1.0
  testingTag: v6.0.1.0
messageQueue:
  type: nats
  name: natsservice
  fullname: natsservice.envronment
  port: 4222
  targetPort: 4222

rbac:
  name: GB28181.platform2016.service
  targetNamespace: video
